/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Estado de salud de la API.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/data-freshness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Freshness
         * @description Frescura de los datos: última fecha de partido y recuentos.
         *
         *     Recuentos directos sobre el esquema de scouting (seasons/competitions/
         *     teams/players/games/upcoming_matchups).
         */
        get: operations["data_freshness_api_v1_meta_data_freshness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description Lista todos los equipos conocidos (id TEXT + nombre + condición de propio).
         */
        get: operations["list_teams_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Detail
         * @description Detalle de un equipo por id TEXT.
         */
        get: operations["get_team_detail_api_v1_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Filters
         * @description Filtros disponibles para un equipo: temporadas y competiciones.
         */
        get: operations["get_filters_api_v1_teams__team_id__filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Resumen del equipo: identidad, filtros aplicados y medias avanzadas.
         */
        get: operations["get_summary_api_v1_teams__team_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description Partidos de un equipo (jugados y pendientes), paginados.
         */
        get: operations["list_games_api_v1_teams__team_id__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roster
         * @description Plantilla de un equipo para una temporada (por defecto la última).
         */
        get: operations["get_roster_api_v1_teams__team_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/rating-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rating Trend
         * @description Tendencia ORtg/DRtg de un equipo en sus últimos N partidos.
         */
        get: operations["get_rating_trend_api_v1_teams__team_id__rating_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/schedule-difficulty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Difficulty
         * @description Dificultad del próximo tramo de calendario (de upcoming_matchups).
         */
        get: operations["get_schedule_difficulty_api_v1_teams__team_id__schedule_difficulty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Narrative
         * @description Narrativa de scouting derivada de los últimos partidos del equipo.
         *
         *     Si no hay datos suficientes, devuelve `narrative: null` (degradado, no
         *     inventa contenido).
         */
        get: operations["get_narrative_api_v1_teams__team_id__narrative_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game Detail
         * @description Detalle completo de un partido (resultado, advanced, lineups, zonas, eventos).
         */
        get: operations["get_game_detail_api_v1_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/boxscore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Boxscore
         * @description Box score de un partido (filas de ambos equipos, sin filtrar por equipo).
         */
        get: operations["get_boxscore_api_v1_games__game_id__boxscore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/players/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Form
         * @description Forma reciente de un jugador (o de todos los de la plantilla si no se da id).
         *
         *     Si `player_id` no se da, devuelve la forma del primer jugador de la
         *     plantilla del equipo (degradado documentado; la SPA debe pasar `player_id`).
         */
        get: operations["get_player_form_api_v1_teams__team_id__players_form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/players/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Load
         * @description Carga de minutos por jugador en la ventana de días (transversal).
         */
        get: operations["get_load_api_v1_teams__team_id__players_load_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upcoming-matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Upcoming Matchups
         * @description Próximos rivales, ordenados por fecha de partido.
         */
        get: operations["list_upcoming_matchups_api_v1_upcoming_matchups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/matchups/{opponent_id}/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Projection
         * @description Proyección de marcador esperado entre dos equipos.
         *
         *     Derivada de las tendencias ORtg/DRtg de ambos equipos y del próximo
         *     enfrentamiento registrado en `upcoming_matchups`. Si no hay datos
         *     suficientes, `projection` es null (degradado, no inventa).
         */
        get: operations["get_projection_api_v1_teams__team_id__matchups__opponent_id__projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/matchups/{opponent_id}/head-to-head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Head To Head
         * @description Enfrentamientos directos entre dos equipos.
         */
        get: operations["get_head_to_head_api_v1_teams__team_id__matchups__opponent_id__head_to_head_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Game
         * @description Encola la recarga de un partido desde su fuente (202, fire-and-forget).
         *
         *     Args:
         *         game_id: id del partido (`"<fuente>-<id externo>"`).
         *         season_label: temporada, obligatoria solo si el partido aún no existe.
         *
         *     Returns:
         *         `RefreshResponse` con `triggered`, `already_in_progress` o
         *         `rejected_busy`.
         *
         *     Raises:
         *         InvalidFilter: la fuente del `game_id` no admite refresco bajo demanda.
         *         GameNotFound: el partido no existe y no se pasó `season_label`.
         */
        post: operations["refresh_game_api_v1_games__game_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discovery/missing-games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Missing Games
         * @description Lista los partidos jugados de la fuente/temporada que faltan en `games`.
         *
         *     `source`/`season_label` inválidos los rechaza la validación de FastAPI con
         *     un 422 `problem+json` (ver `apps/api/errors.py`), sin código propio aquí.
         *
         *     Args:
         *         source: fuente de ingesta (`acb` o `euroleague`).
         *         season_label: temporada en formato `'2025-2026'`.
         *
         *     Returns:
         *         `MissingGamesResponse` con los ids ya prefijados (`"<source>-<id>"`),
         *         listos para `POST /games/{game_id}/refresh?season_label=...`.
         */
        post: operations["discover_missing_games_api_v1_discovery_missing_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdvancedSummary
         * @description Medias de estadísticas avanzadas de un equipo (cada clave puede ser null).
         */
        AdvancedSummary: {
            /** Avg Ortg */
            avg_ortg?: number | null;
            /** Avg Drtg */
            avg_drtg?: number | null;
            /** Avg Net Rating */
            avg_net_rating?: number | null;
            /** Avg Efg Pct */
            avg_efg_pct?: number | null;
            /** Avg Ts Pct */
            avg_ts_pct?: number | null;
            /** Avg Tov Pct */
            avg_tov_pct?: number | null;
            /** Avg Orb Pct */
            avg_orb_pct?: number | null;
            /** Avg Ast Pct */
            avg_ast_pct?: number | null;
            /** Avg Stl Pct */
            avg_stl_pct?: number | null;
            /** Avg Blk Pct */
            avg_blk_pct?: number | null;
            /** Avg Ft Rate */
            avg_ft_rate?: number | null;
            /** Avg Ast To Ratio */
            avg_ast_to_ratio?: number | null;
        };
        /**
         * BaskoniaBlock
         * @description Bloque de Baskonia dentro del detalle de partido.
         */
        BaskoniaBlock: {
            /** Is Home */
            is_home: boolean;
            /** Opponent Id */
            opponent_id: string;
            /** Opponent Name */
            opponent_name: string;
            /** Score For */
            score_for: number;
            /** Score Against */
            score_against: number;
        };
        /**
         * BoxScoreResponse
         * @description Box score de un partido (filas de ambos equipos).
         */
        BoxScoreResponse: {
            /** Game Id */
            game_id: string;
            /** Rows */
            rows: components["schemas"]["BoxScoreRow"][];
        };
        /**
         * BoxScoreRow
         * @description Fila de box score de un jugador en un partido.
         */
        BoxScoreRow: {
            /** Game Id */
            game_id: string;
            /** Player Id */
            player_id: string;
            /** Name */
            name: string;
            /** Team Id */
            team_id: string;
            /** Minutes */
            minutes?: number | null;
            /** Pts */
            pts?: number | null;
            /** Reb */
            reb?: number | null;
            /** Ast */
            ast?: number | null;
            /** Efg Pct */
            efg_pct?: number | null;
        };
        /**
         * CompetitionOption
         * @description Opción de competición para el selector de filtros.
         */
        CompetitionOption: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * DataFreshnessResponse
         * @description Frescura de los datos: última fecha de partido y recuentos.
         */
        DataFreshnessResponse: {
            /** Last Game Date */
            last_game_date: string | null;
            /** Games Total */
            games_total: number;
            /** Players Total */
            players_total: number;
            /** Teams Total */
            teams_total: number;
            /** Upcoming Matchups Total */
            upcoming_matchups_total: number;
        };
        /**
         * DifficultyOpponent
         * @description Rival considerado en la dificultad de calendario.
         */
        DifficultyOpponent: {
            /** Opponent Id */
            opponent_id: string;
            /** Opponent Name */
            opponent_name: string;
            /** Match Date */
            match_date: string;
            /** Is Home */
            is_home: boolean;
            /** Predicted Net Rating */
            predicted_net_rating?: number | null;
            /** Predicted Pace */
            predicted_pace?: number | null;
            /** Predicted Ortg */
            predicted_ortg?: number | null;
            /**
             * Has Scouting Data
             * @default false
             */
            has_scouting_data: boolean;
            /** Key Player Note */
            key_player_note?: string | null;
            /** H2H Wins */
            h2h_wins?: number | null;
            /** H2H Losses */
            h2h_losses?: number | null;
            /** H2H Last Result */
            h2h_last_result?: string | null;
        };
        /**
         * FiltersResponse
         * @description Filtros disponibles para un equipo (cabecera de la app).
         */
        FiltersResponse: {
            /** Seasons */
            seasons: string[];
            /** Default Season */
            default_season: string | null;
            /** Competitions */
            competitions: components["schemas"]["CompetitionOption"][];
        };
        /**
         * GameAdvanced
         * @description Estadísticas avanzadas de un partido (four factors).
         */
        GameAdvanced: {
            /** Ortg */
            ortg?: number | null;
            /** Drtg */
            drtg?: number | null;
            /** Net Rating */
            net_rating?: number | null;
            /** Efg Pct */
            efg_pct?: number | null;
            /** Ts Pct */
            ts_pct?: number | null;
            /** Tov Pct */
            tov_pct?: number | null;
            /** Orb Pct */
            orb_pct?: number | null;
            /** Ast Pct */
            ast_pct?: number | null;
            /** Stl Pct */
            stl_pct?: number | null;
            /** Blk Pct */
            blk_pct?: number | null;
            /** Ft Rate */
            ft_rate?: number | null;
            /** Ast To Ratio */
            ast_to_ratio?: number | null;
        };
        /**
         * GameDetailResponse
         * @description Detalle completo de un partido.
         */
        GameDetailResponse: {
            /** Id */
            id: string;
            /** Season Label */
            season_label: string;
            /** Competition Name */
            competition_name: string;
            home_team: components["schemas"]["TeamRef"];
            away_team: components["schemas"]["TeamRef"];
            /** Game Date */
            game_date: string;
            /** Home Score */
            home_score?: number | null;
            /** Away Score */
            away_score?: number | null;
            /** Pace */
            pace?: number | null;
            /** Narrative */
            narrative?: string | null;
            baskonia?: components["schemas"]["BaskoniaBlock"] | null;
            /** Advanced */
            advanced: components["schemas"]["GameAdvanced"][];
            /** Lineups */
            lineups: components["schemas"]["Lineup"][];
            /** Zone Stats */
            zone_stats: components["schemas"]["ZoneStat"][];
            /** Key Events */
            key_events: components["schemas"]["KeyEvent"][];
        };
        /**
         * GameItem
         * @description Un partido de un equipo (jugado o pendiente).
         */
        GameItem: {
            /** Id */
            id: string;
            /** Date */
            date: string;
            /** Competition Name */
            competition_name: string;
            /** Is Home */
            is_home: boolean;
            opponent: components["schemas"]["TeamRef"];
            /** Team Score */
            team_score?: number | null;
            /** Opponent Score */
            opponent_score?: number | null;
            /** Result */
            result?: string | null;
            /** Pace */
            pace?: number | null;
            advanced?: components["schemas"]["GameAdvanced"] | null;
        };
        /**
         * GamesResponse
         * @description Lista paginada de partidos de un equipo.
         */
        GamesResponse: {
            /** Items */
            items: components["schemas"]["GameItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadToHeadGame
         * @description Un enfrentamiento directo entre dos equipos.
         */
        HeadToHeadGame: {
            /** Id */
            id: string;
            /** Date */
            date: string;
            /** Competition Name */
            competition_name: string;
            /** Team Score */
            team_score?: number | null;
            /** Opponent Score */
            opponent_score?: number | null;
            /** Result */
            result?: string | null;
        };
        /**
         * HeadToHeadResponse
         * @description Enfrentamientos directos entre dos equipos.
         */
        HeadToHeadResponse: {
            team: components["schemas"]["TeamRef"];
            opponent: components["schemas"]["TeamRef"];
            /** Items */
            items: components["schemas"]["HeadToHeadGame"][];
        };
        /**
         * HealthResponse
         * @description Estado de salud de la API.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * KeyEvent
         * @description Evento clave del partido.
         */
        KeyEvent: {
            /** Team Id */
            team_id: string;
            /** Team Name */
            team_name: string;
            /** Quarter */
            quarter?: string | null;
            /** Game Clock */
            game_clock?: string | null;
            /** Label */
            label?: string | null;
        };
        /**
         * Lineup
         * @description Quinteto con su rendimiento en el partido.
         */
        Lineup: {
            /** Id */
            id: number;
            /** Minutes */
            minutes?: number | null;
            /** Plus Minus */
            plus_minus?: number | null;
            /** Players */
            players: components["schemas"]["TeamRef"][];
        };
        /**
         * LoadItem
         * @description Carga de minutos de un jugador en la ventana.
         */
        LoadItem: {
            /** Player Id */
            player_id: string;
            /** Name */
            name: string;
            /** Total Minutes */
            total_minutes: number;
        };
        /**
         * LoadResponse
         * @description Carga de minutos por jugador (transversal a temporada/competición).
         */
        LoadResponse: {
            /** Window Days */
            window_days: number;
            /** As Of */
            as_of: string;
            /** Items */
            items: components["schemas"]["LoadItem"][];
        };
        /**
         * MissingGamesResponse
         * @description Partidos del calendario de la fuente que aún no están cargados.
         *
         *     Solo reporta: este endpoint nunca dispara una carga. Los ids vienen ya
         *     prefijados (`"acb-105370"`, `"euroleague-7"`) para poder pasarlos tal cual a
         *     `POST /games/{game_id}/refresh?season_label=...`.
         *
         *     Attributes:
         *         source: fuente consultada.
         *         season_label: temporada consultada (`'2025-2026'`).
         *         missing_game_ids: ids de partidos jugados/finalizados ausentes de
         *             `games`; lista vacía si no falta ninguno.
         */
        MissingGamesResponse: {
            /**
             * Source
             * @enum {string}
             */
            source: "acb" | "euroleague";
            /** Season Label */
            season_label: string;
            /** Missing Game Ids */
            missing_game_ids: string[];
        };
        /**
         * NarrativeResponse
         * @description Narrativa de scouting (único campo en español de la API).
         */
        NarrativeResponse: {
            /** Team Id */
            team_id: string;
            /** Narrative */
            narrative?: string | null;
        };
        /**
         * PlayerFormItem
         * @description Fila de forma reciente de un jugador en un partido.
         */
        PlayerFormItem: {
            /** Game Id */
            game_id: string;
            /** Game Date */
            game_date: string;
            /** Pts */
            pts?: number | null;
            /** Reb */
            reb?: number | null;
            /** Ast */
            ast?: number | null;
            /** Efg Pct */
            efg_pct?: number | null;
        };
        /**
         * PlayerFormResponse
         * @description Forma reciente de un jugador.
         */
        PlayerFormResponse: {
            /** Player Id */
            player_id: string;
            /** Last N */
            last_n: number;
            /** Items */
            items: components["schemas"]["PlayerFormItem"][];
        };
        /**
         * Projection
         * @description Proyección de marcador esperado entre dos equipos.
         */
        Projection: {
            /** Predicted Net Rating */
            predicted_net_rating?: number | null;
            /** Predicted Pace */
            predicted_pace?: number | null;
            /** Predicted Ortg */
            predicted_ortg?: number | null;
            /** Expected Margin */
            expected_margin?: number | null;
        };
        /**
         * ProjectionResponse
         * @description Proyección de un enfrentamiento (projection puede ser null).
         */
        ProjectionResponse: {
            team: components["schemas"]["TeamRef"];
            opponent: components["schemas"]["TeamRef"];
            projection?: components["schemas"]["Projection"] | null;
        };
        /**
         * RatingTrendItem
         * @description Punto de la tendencia ORtg/DRtg de un equipo.
         */
        RatingTrendItem: {
            /** Game Id */
            game_id: string;
            /** Game Date */
            game_date: string;
            /** Ortg */
            ortg?: number | null;
            /** Drtg */
            drtg?: number | null;
        };
        /**
         * RatingTrendResponse
         * @description Tendencia ORtg/DRtg de un equipo en sus últimos N partidos.
         */
        RatingTrendResponse: {
            /** Team Id */
            team_id: string;
            /** Last N */
            last_n: number;
            /** Items */
            items: components["schemas"]["RatingTrendItem"][];
        };
        /**
         * RefreshResponse
         * @description Resultado de *encolar* un refresco (no del refresco en sí).
         *
         *     El trabajo real corre después en background: `triggered` significa
         *     "aceptado y encolado", no "datos ya disponibles". El cliente comprueba el
         *     resultado reconsultando los endpoints de lectura; si el fetch a la fuente
         *     falla, esos endpoints siguen devolviendo `null`/`[]` (nunca un valor
         *     fabricado).
         *
         *     Attributes:
         *         game_id: id del partido para el que se pidió el refresco.
         *         status: `triggered` (encolado), `already_in_progress` (ya hay un
         *             refresco en curso para ese partido) o `rejected_busy` (límite de
         *             refrescos concurrentes alcanzado; reintentar más tarde).
         */
        RefreshResponse: {
            /** Game Id */
            game_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "triggered" | "already_in_progress" | "rejected_busy";
        };
        /**
         * RosterPlayer
         * @description Jugador de la plantilla con sus medias de temporada.
         */
        RosterPlayer: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Number */
            number?: number | null;
            /** Position */
            position?: string | null;
            /** Team Id */
            team_id: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Photo Url */
            photo_url?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Gp */
            gp?: number | null;
            /** Min Avg */
            min_avg?: number | null;
            /** Pts Avg */
            pts_avg?: number | null;
            /** Reb Avg */
            reb_avg?: number | null;
            /** Ast Avg */
            ast_avg?: number | null;
            /** Efg Pct */
            efg_pct?: number | null;
        };
        /**
         * RosterResponse
         * @description Plantilla de un equipo para una temporada.
         */
        RosterResponse: {
            team: components["schemas"]["TeamRef"];
            /** Season Label */
            season_label: string;
            /** Players */
            players: components["schemas"]["RosterPlayer"][];
        };
        /**
         * ScheduleDifficultyResponse
         * @description Dificultad del próximo tramo de calendario.
         */
        ScheduleDifficultyResponse: {
            /** Games Considered */
            games_considered: number;
            /** Opponents Scouted */
            opponents_scouted: number;
            /** Avg Opponent Net Rating */
            avg_opponent_net_rating?: number | null;
            /** Opponents */
            opponents: components["schemas"]["DifficultyOpponent"][];
        };
        /**
         * SummaryResponse
         * @description Resumen del equipo: identidad, filtros aplicados y medias avanzadas.
         */
        SummaryResponse: {
            team: components["schemas"]["TeamRef"];
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            advanced: components["schemas"]["AdvancedSummary"];
            /** Games Played */
            games_played: number;
            /** Games Upcoming */
            games_upcoming: number;
        };
        /**
         * TeamRef
         * @description Referencia a un equipo (id TEXT + nombre para mostrar).
         */
        TeamRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * TeamResponse
         * @description Equipo con su condición de equipo propio.
         */
        TeamResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Is Own Team */
            is_own_team: boolean;
        };
        /**
         * UpcomingMatchup
         * @description Próximo partido de un equipo (de upcoming_matchups).
         */
        UpcomingMatchup: {
            /** Id */
            id: number;
            opponent: components["schemas"]["TeamRef"];
            /** Competition Name */
            competition_name: string;
            /** Match Date */
            match_date: string;
            /** Is Home */
            is_home: boolean;
            /** Predicted Net Rating */
            predicted_net_rating?: number | null;
            /** Predicted Pace */
            predicted_pace?: number | null;
            /** Predicted Ortg */
            predicted_ortg?: number | null;
            /**
             * Has Scouting Data
             * @default false
             */
            has_scouting_data: boolean;
            /** Key Player Note */
            key_player_note?: string | null;
            /** H2H Wins */
            h2h_wins?: number | null;
            /** H2H Losses */
            h2h_losses?: number | null;
            /** H2H Last Result */
            h2h_last_result?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ZoneStat
         * @description Estadística por zona de la cancha.
         */
        ZoneStat: {
            /** Team Id */
            team_id: string;
            /** Team Name */
            team_name: string;
            /** Zone Id */
            zone_id: number;
            /** Label */
            label: string;
            /** Fg Pct */
            fg_pct?: number | null;
            /** Volume */
            volume?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    data_freshness_api_v1_meta_data_freshness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFreshnessResponse"];
                };
            };
        };
    };
    list_teams_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"][];
                };
            };
        };
    };
    get_team_detail_api_v1_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filters_api_v1_teams__team_id__filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_teams__team_id__summary_get: {
        parameters: {
            query?: {
                /** @description Etiqueta de temporada (p.ej. '2025-2026') */
                season_label?: string | null;
            };
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_v1_teams__team_id__games_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Etiqueta de temporada (p.ej. '2025-2026') */
                season_label?: string | null;
            };
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roster_api_v1_teams__team_id__roster_get: {
        parameters: {
            query?: {
                /** @description Etiqueta de temporada (p.ej. '2025-2026') */
                season_label?: string | null;
            };
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rating_trend_api_v1_teams__team_id__rating_trend_get: {
        parameters: {
            query?: {
                last_n?: number;
            };
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingTrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_difficulty_api_v1_teams__team_id__schedule_difficulty_get: {
        parameters: {
            query?: {
                next_n?: number;
            };
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleDifficultyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_narrative_api_v1_teams__team_id__narrative_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_detail_api_v1_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id TEXT del partido (p.ej. 'g1') */
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_boxscore_api_v1_games__game_id__boxscore_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id TEXT del partido (p.ej. 'g1') */
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_form_api_v1_teams__team_id__players_form_get: {
        parameters: {
            query?: {
                /** @description Id del jugador (opcional) */
                player_id?: string | null;
                last_n?: number;
            };
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerFormResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_api_v1_teams__team_id__players_load_get: {
        parameters: {
            query?: {
                window_days?: number;
                /** @description Fecha de referencia (ISO-8601) */
                as_of?: string | null;
            };
            header?: never;
            path: {
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upcoming_matchups_api_v1_upcoming_matchups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingMatchup"][];
                };
            };
        };
    };
    get_projection_api_v1_teams__team_id__matchups__opponent_id__projection_get: {
        parameters: {
            query?: {
                /** @description Etiqueta de temporada (p.ej. '2025-2026') */
                season_label?: string | null;
            };
            header?: never;
            path: {
                /** @description Id TEXT del rival (p.ej. 'rm') */
                opponent_id: string;
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_head_to_head_api_v1_teams__team_id__matchups__opponent_id__head_to_head_get: {
        parameters: {
            query?: {
                /** @description Etiqueta de temporada (p.ej. '2025-2026') */
                season_label?: string | null;
            };
            header?: never;
            path: {
                /** @description Id TEXT del rival (p.ej. 'rm') */
                opponent_id: string;
                /** @description Id TEXT del equipo (p.ej. 'bas') */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadToHeadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_game_api_v1_games__game_id__refresh_post: {
        parameters: {
            query?: {
                /** @description Temporada del partido (p.ej. '2025-2026'). Solo necesario para cargar un partido que todavía no existe en `games` (descubierto con POST /discovery/missing-games). */
                season_label?: string | null;
            };
            header?: never;
            path: {
                /** @description Id TEXT del partido (p.ej. 'g1') */
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_missing_games_api_v1_discovery_missing_games_post: {
        parameters: {
            query: {
                /** @description Fuente de ingesta a consultar */
                source: "acb" | "euroleague";
                /** @description Temporada a consultar (p.ej. '2025-2026') */
                season_label: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingGamesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
