/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Estado de salud de la API (endpoint 1).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/data-freshness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Freshness
         * @description Frescura de los datos: última fecha de partido y recuentos (endpoint 2).
         */
        get: operations["data_freshness_api_v1_meta_data_freshness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description Lista todos los equipos conocidos (endpoint 3).
         */
        get: operations["list_teams_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Detail
         * @description Detalle de un equipo por slug (endpoint 4).
         */
        get: operations["get_team_detail_api_v1_teams__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Filters
         * @description Filtros disponibles para un equipo: temporadas y competiciones (endpoint 5).
         */
        get: operations["get_filters_api_v1_teams__slug__filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Resumen del equipo: identidad, filtros y medias avanzadas (endpoint 6).
         */
        get: operations["get_summary_api_v1_teams__slug__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description Partidos de un equipo (jugados y pendientes), paginados (endpoint 7).
         */
        get: operations["list_games_api_v1_teams__slug__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/boxscore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Boxscore
         * @description Box score de un equipo en un partido (endpoint 16).
         *
         *     `team_slug` es un query param obligatorio (no va en la ruta).
         */
        get: operations["get_boxscore_api_v1_games__game_id__boxscore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roster
         * @description Plantilla actual de un equipo con la forma reciente de cada jugador (endpoint 8).
         */
        get: operations["get_roster_api_v1_teams__slug__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/players/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Form
         * @description Forma reciente por jugador (endpoint 9).
         */
        get: operations["get_player_form_api_v1_teams__slug__players_form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/players/streaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Streaks
         * @description Rachas de los jugadores en una temporada (endpoint 10).
         */
        get: operations["get_streaks_api_v1_teams__slug__players_streaks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/players/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Load
         * @description Carga de minutos por jugador en la ventana de días (endpoint 11).
         */
        get: operations["get_load_api_v1_teams__slug__players_load_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/schedule-difficulty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Difficulty
         * @description Dificultad del próximo tramo de calendario (endpoint 12).
         */
        get: operations["get_schedule_difficulty_api_v1_teams__slug__schedule_difficulty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Narrative
         * @description Narrativa de scouting en español (endpoint 13).
         */
        get: operations["get_narrative_api_v1_teams__slug__narrative_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/matchups/{opponent_slug}/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Projection
         * @description Proyección de marcador entre dos equipos (endpoint 14).
         */
        get: operations["get_projection_api_v1_teams__slug__matchups__opponent_slug__projection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/matchups/{opponent_slug}/head-to-head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Head To Head
         * @description Enfrentamientos directos entre dos equipos (endpoint 15).
         */
        get: operations["get_head_to_head_api_v1_teams__slug__matchups__opponent_slug__head_to_head_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/reports/scouting.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Report
         * @description Informe de equipo (endpoint 17) — implementado en F6.
         */
        get: operations["team_report_api_v1_teams__slug__reports_scouting_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{slug}/reports/roster.pptx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matchup Report
         * @description Informe de enfrentamiento (endpoint 18) — implementado en F6.
         */
        get: operations["matchup_report_api_v1_teams__slug__reports_roster_pptx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Quality
         * @description Validación de calidad de datos (endpoint 19).
         */
        get: operations["data_quality_api_v1_admin_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdvancedSummary
         * @description Medias de estadísticas avanzadas de un equipo (cada clave puede ser null).
         */
        AdvancedSummary: {
            /** Avg Pace */
            avg_pace?: number | null;
            /** Avg Off Rating */
            avg_off_rating?: number | null;
            /** Avg Def Rating */
            avg_def_rating?: number | null;
            /** Avg Net Rating */
            avg_net_rating?: number | null;
            /** Avg Efg Pct */
            avg_efg_pct?: number | null;
            /** Avg Ts Pct */
            avg_ts_pct?: number | null;
        };
        /**
         * BoxScoreResponse
         * @description Box score de un equipo en un partido.
         */
        BoxScoreResponse: {
            /** Game Id */
            game_id: number;
            team: components["schemas"]["TeamRef"];
            opponent: components["schemas"]["TeamRef"];
            /** Date */
            date: string;
            /** League */
            league: string;
            /** Team Score */
            team_score?: number | null;
            /** Opponent Score */
            opponent_score?: number | null;
            /** Result */
            result?: string | null;
            /** Rows */
            rows: components["schemas"]["BoxScoreRow"][];
        };
        /**
         * BoxScoreRow
         * @description Fila de box score de un jugador en un partido.
         */
        BoxScoreRow: {
            /** Player Name */
            player_name: string;
            /** Minutes */
            minutes?: string | null;
            /** Points */
            points?: number | null;
            /** Rebounds */
            rebounds?: number | null;
            /** Assists */
            assists?: number | null;
            /** Steals */
            steals?: number | null;
            /** Blocks */
            blocks?: number | null;
            /** Turnovers */
            turnovers?: number | null;
            /** Fg Made */
            fg_made?: number | null;
            /** Fg Attempted */
            fg_attempted?: number | null;
            /** Fg3 Made */
            fg3_made?: number | null;
            /** Fg3 Attempted */
            fg3_attempted?: number | null;
            /** Ft Made */
            ft_made?: number | null;
            /** Ft Attempted */
            ft_attempted?: number | null;
            /** Efg Pct */
            efg_pct?: number | null;
            /** Ts Pct */
            ts_pct?: number | null;
        };
        /**
         * DataFreshnessResponse
         * @description Frescura de los datos: última fecha de partido y recuentos.
         */
        DataFreshnessResponse: {
            /** Last Game Date */
            last_game_date: string | null;
            /** Games Total */
            games_total: number;
            /** Boxscores Total */
            boxscores_total: number;
            /** Teams Total */
            teams_total: number;
        };
        /**
         * DataQualityResponse
         * @description Resultado de la validación de calidad de datos.
         */
        DataQualityResponse: {
            /** Warnings */
            warnings: string[];
            /** Healthy */
            healthy: boolean;
        };
        /**
         * DifficultyOpponent
         * @description Rival considerado en la dificultad de calendario.
         */
        DifficultyOpponent: {
            /** Opponent Name */
            opponent_name: string;
            /** Date */
            date: string;
            /** Net Rating */
            net_rating?: number | null;
        };
        /**
         * FiltersResponse
         * @description Filtros disponibles para un equipo (cabecera de la app).
         */
        FiltersResponse: {
            /** Seasons */
            seasons: number[];
            /** Default Season */
            default_season: number | null;
            /** Leagues */
            leagues: components["schemas"]["LeagueOption"][];
        };
        /**
         * GameAdvanced
         * @description Estadísticas avanzadas de un equipo en un partido.
         */
        GameAdvanced: {
            /** Pace */
            pace?: number | null;
            /** Off Rating */
            off_rating?: number | null;
            /** Def Rating */
            def_rating?: number | null;
            /** Net Rating */
            net_rating?: number | null;
        };
        /**
         * GameItem
         * @description Un partido de un equipo (jugado o pendiente).
         */
        GameItem: {
            /** Id */
            id: number;
            /** Date */
            date: string;
            /** League */
            league: string;
            /** Is Home */
            is_home: boolean;
            opponent: components["schemas"]["TeamRef"];
            /** Team Score */
            team_score?: number | null;
            /** Opponent Score */
            opponent_score?: number | null;
            /** Result */
            result?: string | null;
            /** Notes */
            notes?: string | null;
            advanced?: components["schemas"]["GameAdvanced"] | null;
            /**
             * Has Boxscore
             * @default false
             */
            has_boxscore: boolean;
        };
        /**
         * GamesResponse
         * @description Lista paginada de partidos de un equipo.
         */
        GamesResponse: {
            /** Items */
            items: components["schemas"]["GameItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadToHeadGame
         * @description Un enfrentamiento directo entre dos equipos.
         */
        HeadToHeadGame: {
            /** Id */
            id: number;
            /** Date */
            date: string;
            /** League */
            league: string;
            /** Team Score */
            team_score?: number | null;
            /** Opponent Score */
            opponent_score?: number | null;
            /** Result */
            result?: string | null;
        };
        /**
         * HeadToHeadResponse
         * @description Enfrentamientos directos entre dos equipos.
         */
        HeadToHeadResponse: {
            team: components["schemas"]["TeamRef"];
            opponent: components["schemas"]["TeamRef"];
            /** Items */
            items: components["schemas"]["HeadToHeadGame"][];
        };
        /**
         * HealthResponse
         * @description Estado de salud de la API.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LeagueOption
         * @description Opción de competición para el selector de filtros.
         */
        LeagueOption: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /**
         * LoadItem
         * @description Carga de minutos de un jugador en la ventana.
         */
        LoadItem: {
            /** Player Name */
            player_name: string;
            /** Games */
            games: number;
            /** Total Minutes */
            total_minutes: number;
            /** Avg Minutes */
            avg_minutes: number;
        };
        /**
         * LoadResponse
         * @description Carga de minutos por jugador (transversal a temporada/competición).
         */
        LoadResponse: {
            /** Window Days */
            window_days: number;
            /** Games In Window */
            games_in_window: number;
            /** Note */
            note: string;
            /** Items */
            items: components["schemas"]["LoadItem"][];
        };
        /**
         * NarrativeResponse
         * @description Narrativa de scouting (único campo en español de la API).
         */
        NarrativeResponse: {
            /** Season */
            season: number;
            /** League */
            league?: string | null;
            /** Recent N */
            recent_n: number;
            /** Narrative */
            narrative?: string | null;
        };
        /**
         * PlayerFormItem
         * @description Fila de forma reciente por jugador (mapeo 1:1 con player_recent_form).
         */
        PlayerFormItem: {
            /** Player Name */
            player_name: string;
            /** Games */
            games: number;
            /** Avg Minutes */
            avg_minutes?: number | null;
            /** Avg Pts */
            avg_pts?: number | null;
            /** Avg Pts Per36 */
            avg_pts_per36?: number | null;
            /** Avg Efg Pct */
            avg_efg_pct?: number | null;
            /** Avg Ts Pct */
            avg_ts_pct?: number | null;
            /** Avg Plus Minus */
            avg_plus_minus?: number | null;
            /** Avg Turnovers */
            avg_turnovers?: number | null;
            /** Fg3A Rate */
            fg3a_rate?: number | null;
            /** Ft Rate */
            ft_rate?: number | null;
        };
        /**
         * PlayerFormResponse
         * @description Forma reciente por jugador.
         */
        PlayerFormResponse: {
            /** Last N */
            last_n: number;
            /** Items */
            items: components["schemas"]["PlayerFormItem"][];
        };
        /**
         * Projection
         * @description Proyección de marcador esperado entre dos equipos.
         */
        Projection: {
            /** Projected Possessions */
            projected_possessions: number;
            /** Team Projected Rating */
            team_projected_rating: number;
            /** Opp Projected Rating */
            opp_projected_rating: number;
            /** Team Projected Score */
            team_projected_score: number;
            /** Opp Projected Score */
            opp_projected_score: number;
            /** Expected Margin */
            expected_margin: number;
        };
        /**
         * ProjectionResponse
         * @description Proyección de un enfrentamiento (projection puede ser null).
         */
        ProjectionResponse: {
            team: components["schemas"]["TeamRef"];
            opponent: components["schemas"]["TeamRef"];
            /** Season */
            season: number;
            projection?: components["schemas"]["Projection"] | null;
        };
        /**
         * ReportNotImplemented
         * @description Respuesta de los endpoints de informes en F3 (se completan en F6).
         */
        ReportNotImplemented: {
            /** Detail */
            detail: string;
        };
        /**
         * RosterPlayer
         * @description Jugador de la plantilla actual con su forma reciente.
         */
        RosterPlayer: {
            /** Name */
            name: string;
            /** Number */
            number?: string | null;
            /** Position */
            position?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Form */
            form?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RosterResponse
         * @description Plantilla actual de un equipo.
         */
        RosterResponse: {
            team: components["schemas"]["TeamRef"];
            /** Players */
            players: components["schemas"]["RosterPlayer"][];
        };
        /**
         * ScheduleDifficultyResponse
         * @description Dificultad del próximo tramo de calendario.
         */
        ScheduleDifficultyResponse: {
            /** Games Considered */
            games_considered: number;
            /** Opponents Scouted */
            opponents_scouted: number;
            /** Avg Opponent Net Rating */
            avg_opponent_net_rating?: number | null;
            /** League */
            league?: string | null;
            /** Opponents */
            opponents: components["schemas"]["DifficultyOpponent"][];
        };
        /**
         * StreakItem
         * @description Racha de un jugador dentro de una temporada.
         */
        StreakItem: {
            /** Player Name */
            player_name: string;
            /** Games Season */
            games_season: number;
            /** Recent Avg Pts */
            recent_avg_pts?: number | null;
            /** Season Avg Pts */
            season_avg_pts?: number | null;
            /** Season Std Pts */
            season_std_pts?: number | null;
            /** Z Score Pts */
            z_score_pts?: number | null;
            /** Recent Avg Ts Pct */
            recent_avg_ts_pct?: number | null;
            /** Season Avg Ts Pct */
            season_avg_ts_pct?: number | null;
            /** Season Std Ts Pct */
            season_std_ts_pct?: number | null;
            /** Z Score Ts */
            z_score_ts?: number | null;
            /** Label */
            label: string;
        };
        /**
         * StreaksResponse
         * @description Rachas de los jugadores de un equipo en una temporada.
         */
        StreaksResponse: {
            /** Season */
            season: number;
            /** Recent N */
            recent_n: number;
            /** Min Season Games */
            min_season_games: number;
            /** Items */
            items: components["schemas"]["StreakItem"][];
        };
        /**
         * SummaryResponse
         * @description Resumen del equipo: identidad, filtros aplicados y medias avanzadas.
         */
        SummaryResponse: {
            team: components["schemas"]["TeamRef"];
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            advanced: components["schemas"]["AdvancedSummary"];
            /** Games Played */
            games_played: number;
            /** Games Upcoming */
            games_upcoming: number;
        };
        /**
         * TeamRef
         * @description Referencia a un equipo (slug + nombre para mostrar).
         */
        TeamRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /**
         * TeamResponse
         * @description Equipo con su liga de origen.
         */
        TeamResponse: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** League */
            league: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    data_freshness_api_v1_meta_data_freshness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFreshnessResponse"];
                };
            };
        };
    };
    list_teams_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"][];
                };
            };
        };
    };
    get_team_detail_api_v1_teams__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filters_api_v1_teams__slug__filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_teams__slug__summary_get: {
        parameters: {
            query?: {
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_v1_teams__slug__games_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_boxscore_api_v1_games__game_id__boxscore_get: {
        parameters: {
            query: {
                /** @description Slug del equipo cuyo box score se pide */
                team_slug: string;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roster_api_v1_teams__slug__roster_get: {
        parameters: {
            query?: {
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_form_api_v1_teams__slug__players_form_get: {
        parameters: {
            query?: {
                last_n?: number;
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerFormResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_streaks_api_v1_teams__slug__players_streaks_get: {
        parameters: {
            query?: {
                recent_n?: number;
                min_season_games?: number;
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreaksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_api_v1_teams__slug__players_load_get: {
        parameters: {
            query?: {
                window_days?: number;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_difficulty_api_v1_teams__slug__schedule_difficulty_get: {
        parameters: {
            query?: {
                next_n?: number;
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleDifficultyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_narrative_api_v1_teams__slug__narrative_get: {
        parameters: {
            query?: {
                recent_n?: number;
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projection_api_v1_teams__slug__matchups__opponent_slug__projection_get: {
        parameters: {
            query?: {
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
                /** @description Slug del rival (p.ej. 'bilbao') */
                opponent_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_head_to_head_api_v1_teams__slug__matchups__opponent_slug__head_to_head_get: {
        parameters: {
            query?: {
                /** @description Año de inicio de temporada (p.ej. 2025) */
                season?: number | null;
                /** @description Competición: acb | euroleague | supercopa */
                league?: string | null;
            };
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
                /** @description Slug del rival (p.ej. 'bilbao') */
                opponent_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadToHeadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_report_api_v1_teams__slug__reports_scouting_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportNotImplemented"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportNotImplemented"];
                };
            };
        };
    };
    matchup_report_api_v1_teams__slug__reports_roster_pptx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug del equipo (p.ej. 'vitoria') */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportNotImplemented"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportNotImplemented"];
                };
            };
        };
    };
    data_quality_api_v1_admin_data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityResponse"];
                };
            };
        };
    };
}
